name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey! thanks for bringing this issue to attention! Will take a look as soon as I can.'
        pr-message: 'Hey! thanks for the improvement. Will get to it as soon as I can. Good Luck.'
